-- V1 — baseline do schema (multi-tenant por coluna conta_id).

CREATE TABLE conta (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                VARCHAR(255) NOT NULL,
    email               VARCHAR(255) NOT NULL UNIQUE,
    senha_hash          VARCHAR(255) NOT NULL,
    bot_deep_link_token VARCHAR(64)  NOT NULL UNIQUE,
    criado_em           TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE horario_atendimento (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id    BIGINT     NOT NULL REFERENCES conta(id) ON DELETE CASCADE,
    dia_semana  VARCHAR(10) NOT NULL,
    hora_inicio TIME       NOT NULL,
    hora_fim    TIME       NOT NULL
);
CREATE INDEX idx_horario_conta ON horario_atendimento(conta_id);

CREATE TABLE servico (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id    BIGINT       NOT NULL REFERENCES conta(id) ON DELETE CASCADE,
    nome        VARCHAR(255) NOT NULL,
    duracao_min INT          NOT NULL,
    descricao   VARCHAR(1000),
    preco       NUMERIC(10,2),
    ativo       BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_servico_conta ON servico(conta_id);

CREATE TABLE cliente (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id         BIGINT       NOT NULL REFERENCES conta(id) ON DELETE CASCADE,
    nome             VARCHAR(255) NOT NULL,
    telegram_user_id BIGINT,
    telefone         VARCHAR(30),
    origem           VARCHAR(10)  NOT NULL,
    criado_em        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_cliente_identidade CHECK (telegram_user_id IS NOT NULL OR telefone IS NOT NULL)
);
CREATE INDEX idx_cliente_conta ON cliente(conta_id);

CREATE TABLE agendamento (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_id      BIGINT      NOT NULL REFERENCES conta(id) ON DELETE CASCADE,
    cliente_id    BIGINT      NOT NULL REFERENCES cliente(id),
    servico_id    BIGINT      NOT NULL REFERENCES servico(id),
    inicio        TIMESTAMP   NOT NULL,
    fim           TIMESTAMP   NOT NULL,
    preco_cobrado NUMERIC(10,2),
    status        VARCHAR(12) NOT NULL,
    origem        VARCHAR(10) NOT NULL,
    criado_em     TIMESTAMPTZ NOT NULL,
    atualizado_em TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_agendamento_conta_inicio ON agendamento(conta_id, inicio);
