package com.plataforma.agendamentos.adapter.in.telegram;

enum BotStep {
    AGUARDANDO_SERVICO,
    AGUARDANDO_DATA,
    AGUARDANDO_SLOT,
    AGUARDANDO_CANCELAMENTO_SELECAO,
    AGUARDANDO_REMARCAR_SELECAO,
    AGUARDANDO_REMARCAR_NOVA_DATA,
    AGUARDANDO_REMARCAR_NOVO_SLOT
}
